### ISSUE TITLE
Performing bulk action "move all" leaks memory

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-files#174]
When performing the bulk action "move all" repeatedly, the server's memory slowly increases (1MB~ for 100 files moved).

**Comment by frankrousseau** [comment]
Is the memory never freed?

**Comment by jsilvestre** [comment]
I don't know, I never pushed the investigation further, I'm super bad at that.

**Comment by frankrousseau** [comment]
The issue is old and noone complained about this. Let's close it.
