### ISSUE TITLE
File is shown twice after upload

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-files#196]
I have found and investigated a bug, but wasn't able to reproduce in a stable way. Sometimes after a successful upload, the uploaded element is displayed twice: 
* as an element like it should be
* as an element with a progress bar like it was during upload

The best way I found to reproduce *sometimes*:
* in an empty folder
* add a file (don't click on the "ok" button in the upload status bar)
* remove that file
* click the "ok" button in the upload status bar
* add another file

If you are "lucky", you will get the bug.

Evidence tends to prove the responsible is the ViewCollection where at some point, a removal just doesn't work for no reason.

One fix could be to use ReactJS which is basically meant to solve this kind of problem with no headache. Another fix would be to track down and clean every single event interaction between the source collection (which is a merge of two collections) and the view collection.

**Comment by frankrousseau** [comment]
Should be fixed with recent changes. Let's see if someone complains.
