### ISSUE TITLE
File disappear

### ISSUE THREAD

**Issue by nledez** [cozy/cozy-files#212]
Hello,

today a file disappear from my listing:
- With Firefox 34.0 on OSX Yosemine
- In an empty folder
- Drag&drop a photo
- I have the tooltip "One file successfully uploaded"
- Click on share button
- Select "Public"
- Copy link
- Validate with "Save"

And the image is missing.

Reappear on "One file successfully uploaded" validation message.

**Comment by clochix** [comment]
@nledez any news on this ?

**Comment by nledez** [comment]
It's fixed.

Thanks.
