### ISSUE TITLE
Don't zip when there is only one file

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-files#224]
@goofy-bz mentioned that he downloaded a file, and that file was zipped before download.

source: https://forum.cozy.io/t/telechargement-dun-seul-fichier-inutilement-compresse-en-zip/229

**Comment by clochix** [comment]
@goofy-bz I think this has been foxed for some time now, could you give it a try?

**Comment by poupotte** [comment]
It works well for me. I close this issue, @goofy-bz , if you have still this problem, don't hesistate to reopen it.
