### ISSUE TITLE
Store mimetype on File document

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-files#227]
Mimetype is often useful when dealing with files metadata. It would make things easier to have it directly stored. What do you think?

**Comment by aenario** [comment]
You've already done this in 640883db9ac369eb and the mimetype was accurate in my tests. 
Do you want to make a patch for Files created before Jul16 ?

**Comment by frankrousseau** [comment]
No, it's ok. But I'm wondering why I opened that issue.

**Comment by frankrousseau** [comment]
I think currently we store the "type" (the category) of the file and not the full mimetype.

**Comment by aenario** [comment]
We store both. 
- the "type" property, which is a very small set, guided by the available icons 
- the "mime" property, which is the result of mime.lookup on the file.

**Comment by frankrousseau** [comment]
Ok good. Thank you for the information.

**Comment by aenario** [comment]
@frankrousseau , you moved this card back to Doing in Trello ?
