### ISSUE TITLE
Public download of a folder

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-files#229]
A friend of mine reported that when he downloads all the files of a folder that has been shared with him, the zip archive is corrupted.

Information:
* cozy-files is up-to-date
* there 61 elements of 3.5 MB each
* the zip file is roughly 185 MB

After many tries, he managed to successfully retrieve the file, but it should just work.

**Comment by frankrousseau** [comment]
Do you have a stacktrace?

**Comment by jsilvestre** [comment]
No, sorry. The zip file cannot be opened, that's all. I give you the Cozy where it happens in private, we host it.

**Comment by Flaburgan** [comment]
This happened on flaburgan.cozycloud.cc so you can check the logs there. You have to know that there were some crashes during the upload of the image files (a few months ago), so it's possible that the data are corrupted and this is why the zip is broken. We should probably try with new clean data.

**Comment by jsilvestre** [comment]
So we managed to reproduce the bug with @Flaburgan's data set. I'm not sure data are corrupted, it's not impossible the way it's structured cause the ZIP to be corrupted (like subfolders or something).

**Comment by clochix** [comment]
@aenario do you think you will have some time during current sprint to have a look at this ?

**Comment by frankrousseau** [comment]
I think the problem comes from the MP4 file.

**Comment by jsilvestre** [comment]
So I tried again, it worked, but I didn't have all the files. @frankrousseau is it what you talked about? Like @Flaburgan said, there was corrupted files and they are not in the archive?

**Comment by frankrousseau** [comment]
Yes, some files are missing (there is only metadata). So they can't be added to the archive.

**Comment by jsilvestre** [comment]
Should we open a separate issue to detect that kind of "broken files", and close that one?

**Comment by frankrousseau** [comment]
What do you want to do with broken files?

**Comment by Flaburgan** [comment]
At least tell the users that some files are broken?

**Comment by jsilvestre** [comment]
That's what I had in mind, yes.

**Comment by clochix** [comment]
@frankrousseau any news on this ?

**Comment by frankrousseau** [comment]
Sorry for the late reply. I think we can close that one. I'm working on a way to display broken files (without binaries) in the file list.

**Comment by frankrousseau** [comment]
Broken files are now displayed with an informative message in the Files UI.
