### ISSUE TITLE
Improve performance of first rendering

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-files#244]
The first time I open the application, it takes a very long time before displaying anything. I just get a grey screen for 20 seconds.
We should improve the user experience of first rendering, at least by adding a spinner to let the user know the application is not broken.

**Comment by frankrousseau** [comment]
Yes, that's definitely a big issue.

**Comment by jsilvestre** [comment]
How to fix:
* https://github.com/cozy/cozy-proxy/blob/master/server/config.coffee
* https://github.com/cozy/cozy-proxy/blob/master/server/helpers/get_template_ext.coffee
* https://github.com/cozy/cozy-proxy/blob/master/Cakefile
* https://github.com/cozy/cozy-proxy/blob/master/server/controllers/authentication.coffee#L15 and https://github.com/cozy/cozy-proxy/blob/master/server/controllers/authentication.coffee#L24

This is definitely a mutualization issue.

**Comment by frankrousseau** [comment]
I understand nothing to your links.

**Comment by jsilvestre** [comment]
I updated my comment with an explanation, sorry, it was on IRC, and I've been to lazy to copy/paste it here :p

**Comment by aenario** [comment]
link https://github.com/cozy/americano/issues/31

**Comment by jsilvestre** [comment]
It should be fixed in cdba4b1ae216a9e803e0515fdfac94731c6264e5. Let me know if we can close the issue, or if it's not good enough yet.

**Comment by frankrousseau** [comment]
It works well for me thank you @clochix for reporting and thank you @jsilvestre for the fix.
