### ISSUE TITLE
Problem to add a big file (1Go) in my cozy

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-files#251]
Javascript console : 
```
POST https://bellot-zoe.cozycloud.cc/apps/files/files/ [HTTP/1.1 504 Gateway Time-out 60010ms]
POST https://bellot-zoe.cozycloud.cc/apps/files/files/ [0ms]
"Upload Error" "/VIrtualbox/cozycloud-virtualimage.zip" "Le fichier n'a pas pu être envoyé au serveur" app-7c2b1c22.js:632:0
Error in parsing value for 'width'.  Declaration dropped.
```

**Comment by jsilvestre** [comment]
This is related to cozycloud.cc's infrastructure and I have no idea on how to fix it :-/

**Comment by frankrousseau** [comment]
@nledez @LucsT @Kloadut any idea?

**Comment by poupotte** [comment]
Mmmmm... I tested 3 or 4 times before opened this issue. Each time, I had this error. 
However, I test again today, and it works. I don't know why ! Maybe, a better connection or an update.

**Comment by frankrousseau** [comment]
Ok so let's close it and focus on other stuff like calendar sync and currently opened pull requests.
