### ISSUE TITLE
[FRENCH] Problème de partage par lien

### ISSUE THREAD

**Issue by adrien80080** [cozy/cozy-files#253]
Lors du partage par lien, le lien généré utilise le domaine d'accès.
Quand j'accède à CozyCloud en local, via 192.168.1.X, le lien généré est donc https://192.168.1.X/public... au lieu de https://domaine.tld:port/public...

C'est assez gênant quad je me trouve sur le même réseau que le serveur CozyCloud.
Newebe indique que les lignes de codes en cause sont les suivantes : 
https://github.com/cozy/cozy-files/blob/master/client/app/models/file.coffee#L93-L99

Le seul moyen quand on accède à son CozyCloud en intranet est de modifier le fichier host de votre ordinateur en ajoutant la ligne suivante : 
IPSERVEURCC [Tab] DOMAINECC

**Comment by frankrousseau** [comment]
Merci @adrien80080 pour ce rapport de bug. Nous l'ajoutons à notre todo list.

**Comment by clochix** [comment]
Works for me, will be available to users early next week, thanks a lot @poupotte ☺

**Comment by clochix** [comment]
@adrien80080 merci pour la signalement, ça devrait être corrigé dans la version que nous avons publiée ce week-end, n'hésite pas à ré-ouvrir le ticket si tu as encore des soucis.
