### ISSUE TITLE
Unable to set files or folders as private

### ISSUE THREAD

**Issue by vaz-ar** [cozy/cozy-files#260]
Version  1.1.4 

Every time I try to set a file or folder as private and save, it still appears as shared the next time I open the "share" pop up.

**Comment by jsilvestre** [comment]
Apparently it's not a bug, it's a feature: https://github.com/cozy/cozy-files/blob/master/client/app/views/modal_share.coffee#L28

I'm going to talk with the team so we can improve the experience.

**Comment by jsilvestre** [comment]
So we won't change this, I'm closing the issue. Let us know if you have any idea on how to improve your experience.
