### ISSUE TITLE
Checkbox apply to all conflict doesn't work

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-files#264]
A user reported on the forum that the checkbox "apply to all conflict" doesn't work, whatever the choice is.

**Comment by jsilvestre** [comment]
I didn't manage to reproduce this bug. @clochix would you mind doing a double-check please?

**Comment by clochix** [comment]
FTR, here's the source of the report https://forum.cozy.io/t/checkbox-apply-to-all-conflict-doenst-work-in-files-app/493

**Comment by clochix** [comment]
I'm also unable to reproduce this bug, neither by uploading nor drag'n'dropping files.

**Comment by clochix** [comment]
We asked more details to the user on forum, waiting for its answer.

**Comment by jsilvestre** [comment]
Since we didn't get an answer, we're closing for now.
