### ISSUE TITLE
Sharing activation button is not very intuitive

### ISSUE THREAD

**Issue by carrieje** [cozy/cozy-files#265]
There is no icon. There is just a tooltip on hover.
Even the colors (green and orange) are not meaningful from my point of view.

This is not functionally blocking but I had to dig to know if it was a bug or a feature ;-)
![capture du 2015-04-16 00 28 59](https://cloud.githubusercontent.com/assets/4522528/7170582/bde4206c-e3cf-11e4-89e1-28de9f97f10a.png)

**Comment by carrieje** [comment]
As of today (maybe due to a restart of my instance) the problem is solved.
I don't know if you act to solve it but I can see a "share" icon now :-)

**Comment by frankrousseau** [comment]
Great, that bug was weird. Whatever, thank you for reporting!
