### ISSUE TITLE
"Mail not sent" error is not explicit

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-files#267]
An user reported that when he tried to share a folder, it displayed a "mail not sent" error. It was due to the fact he didn't configure his domain in the Home configuration page. The error message should have tell it that something was wrong.

**Comment by clochix** [comment]
Seems like lot of users have this kind of problem on self hosted instances. We should try to fix it for every application that send emails (files, calendar, photo…)

**Comment by poupotte** [comment]
This issue is fixed in [DS](https://github.com/cozy/cozy-data-system/pull/140), [cozy-clearance](https://github.com/cozy/cozy-clearance/pull/23) and [cozy-db](https://github.com/cozy/cozy-db/pull/20).
Wait new versions (cozy-db and cozy-clearance) to upgrade files dependencies.

**Comment by frankrousseau** [comment]
New versions are published.

**Comment by clochix** [comment]
Awesome @poupotte, it works like a charm now ! Thanks !!!
