### ISSUE TITLE
"Mail not send" error contains a typo

### ISSUE THREAD

**Issue by carrieje** [cozy/cozy-files#268]
Error should be

> Mail not sen**t**

I wish I could just make a pull request, but I'm absolutely not familiar with internationalization.
And as far as I can see, there is a dependency for this string with typo in project cozy-clearance.

Sorry I can just report the issue ;-)

cozy-files/client/vendor/scripts/clearance_modal.js line 699

**Comment by clochix** [comment]
Thanks @carrieje for the report and @poupotte for the fix ☺
The fixed version should be available early next week.
