### ISSUE TITLE
Duplicate display of new folder (but created once)

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-files#277]
Hi,

when  creating a new folder __inside__ an existing one (not at the root) 
Once validating the name of the new folder, it is diplayed twice (but not created twice)

Tjhis ticket is close to https://github.com/cozy/cozy-files/issues/272 , but I am not sure they are exactly the same.

**Comment by jsilvestre** [comment]
Hello @ZeHiro and thank you for your report.
Could you try the development branch and tell me if it still happens by any chance? Or wait for the release that will come in the next few days.

My fixes for #272 should solve it (from what I see, your issue is one part of #272).

**Comment by ZeHiro** [comment]
Hi @jsilvestre,
the last version of Files fixes it.
Thanks
