### ISSUE TITLE
Timeout when downloading files (especially big ones)

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-files#279]
A user reported that download requests time out. When he tries to download a 200MB files with a download of 160KB/s, it stops at 60MB.
Other users reported same kind of problem.

**Comment by dascritch** [comment]
Downloads hangup at different positions each time, between 10% to 60% of the content loaded.
Wget reports that the download is closed server-side.

**Comment by dascritch** [comment]
Well, seems that doesn't support partial content downloading. So wget -c is not working.

**Comment by jsilvestre** [comment]
Hi,
I opened a new issue for the partial content downloading support: https://github.com/cozy/cozy-files/issues/284.

I'm currently investigating the timeout issue during downloads. Any further information could be useful.

**Comment by frankrousseau** [comment]
@jsilvestre I think we added long timeouts for the upload. We can probably do the same for uploads.
