### ISSUE TITLE
Sharing to a specific person is case sensitive

### ISSUE THREAD

**Issue by carrieje** [cozy/cozy-files#287]
Here is the contact I have which are concerned (I carefully respected the case as in my contact list)
> Jean-Yves C... \<...jy@...>
> Jean-François C... \<jean-francois...@...>
> Jean-yves N... \<jy...@...>

When I try to search for a specific contact when sharing a directory I have :
* When typing `jean`
  * **Jean**-François C... \<**jean**-francois...@...>
* When typing `Jean`
  * **Jean**-Yves C... \<...jy@...>
  * **Jean**-François C... \<**jean**-francois...@...>
  * **Jean**-yves N... \<jy...@...>
* When typing `JEAN`
  * No result

**Comment by jsilvestre** [comment]
Thank you for reporting!

**Comment by carrieje** [comment]
Thanks !
Will try this as soon as it will be shipped ;-)

**Comment by jsilvestre** [comment]
It should be available in v1.1.8. Let me know if something is still wrong.

**Comment by carrieje** [comment]
:+1:
