### ISSUE TITLE
Allow to deselect files by clicking outside of the file list

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-files#296]
When I select files, I would like an easy way to unselect them all. A common way to do it, is to click outside of the file list.

**Comment by f6fvy** [comment]
:+1:

**Comment by clochix** [comment]
@frankrousseau @f6fvy This should have been enabled in the new version of Files, could you give it a try ?

**Comment by f6fvy** [comment]
Ok for me.

**Comment by clochix** [comment]
Thanks @f6fvy ☺
