### ISSUE TITLE
Selection problems

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-files#300]
@goofy-bz just reported he has sometime problems selecting files. I open this issue so he can describe the STR.

**Comment by clochix** [comment]
In fact, it seems that you can't select the file by clicking on it's icon, whereas the cursor indicates the icon is clickable (and the previous behavior was to click on the icon to select the file)

**Comment by clochix** [comment]
Awesome @poupotte, works really well now ☺
@goofy-bz can you update your Files application and confirm it now works as you expected ?
Thanks to both of you.

**Comment by goofy-bz** [comment]
![goofexcited](https://cloud.githubusercontent.com/assets/858630/8458661/9e627b64-2018-11e5-8a5b-d23f5f2b6bf9.png)

I am overwhelmed with joy and just spent 2 hours selecting like mad.
Am currently busy erecting a giant statue of Poupotte in my garden.

**Comment by clochix** [comment]
Photo or it didn't happen.
Thanks ☺
