### ISSUE TITLE
can't share a file from my pocketcomputer!

### ISSUE THREAD

**Issue by Thatoo** [cozy/cozy-files#301]
If I use Files from my pocket computer, I can only open a file.
I don't about the need for etiquette and download button but the sharing button is definitely needed.
I want to share a video with my friends, instead of using a service like wetransfert.com, and because eamil can't send big attached files, it would be great to use cozy-files, and for that , we need the share button.

**Comment by clochix** [comment]
Hello @Thatoo,

I'm not sure to understand. Is your problem related to the fact that files actions only show up when hovering the screen, and are not available on touch screens ?

**Comment by Thatoo** [comment]
@clochix , when I open cozy-files in my pocketcomputer (I check FFOX and android), there is not "share button next to the files. So I didn't find how I could share a files (like it's possible to do when I use cozy-files on my laptop).

**Comment by clochix** [comment]
Ok, on small screens, actions are not available. They neither show up on touch screen.
@m4dz, @kelukelu, any design idea to make all actions available on small and touch screens ?

**Comment by m4dz** [comment]
IMO, the way we do the RWD in the whole Files app needs to be revamped as we do in emails. I'll try to find some time to quick fix this issue, but we should keep in mind that Files is probably one of our next big rework :smile:.

**Comment by Thatoo** [comment]
@m4dz if cozy-files is the next big rework, then, it can wait I guess. Thank you anyway for taking care of it.

**Comment by poupotte** [comment]
I close this issue, you can follow this issue on https://github.com/cozy/cozy-files/issues/392.
