### ISSUE TITLE
Allow to import document of other types than images/music/video on mobile devices

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-files#304]
Hi,

I tried to upload a document from my cell phone (Android 4.x + Firefox mobile) using the file app from firefox. I chose this solution as the sync android client only uploads photos. 

In the file app, I clickes on the icon of a document with a + on it, and android only allowed me to choose a "picture-provider" app : 
 -Gallery
- Camera
- Music

The "file manager" wasn't proposed. It is then only possible to upload photo/music to the cozy from my device.

**Comment by aenario** [comment]
Hey @ZeHiro , 

Could you try this page : https://bug671833.bugzilla.mozilla.org/attachment.cgi?id=546135 and tell us if none, both or only one of the two buttons have the behaviour you describe.

Thanks,
Romain

**Comment by ZeHiro** [comment]
Hey,
they both have the behaviour I describe.
I wonder if this is due to the android API which don't allow to upload other types of files

**Comment by aenario** [comment]
@ZeHiro , Is there a website you know where you can upload from android with the 

If I recall correctly, most browsers will trigger a Intent.ACTION_GET_CONTENT when clicking on an <input type="file">. Android then display the list of apps which can handle this Intent. So I guess you will need to install a file manager which does (I dont know of any).

**Comment by ZeHiro** [comment]
@aenario 

I was looking for one, but I don't see one, i'll comebacke to you when I find one.

**Comment by jsilvestre** [comment]
Apparently this is an issue with Android, not with Cozy. We'll reopen later if necessary.
