### ISSUE TITLE
when creating a new folder, we have to erase its name

### ISSUE THREAD

**Issue by tykayn** [cozy/cozy-files#305]
instead of having a placeholder into the input, it is the value of the new folder that is set into the input.
so we have to erase the name, instead of just typing its name.
it would be a good UX enhancement.

**Comment by clochix** [comment]
Hello @tykayn,
In fact, the value of the new folder name is selected, so just typing will override it. But you're right, a placeholder will better do the job, thanks for noticing.

**Comment by clochix** [comment]
Hi @tykayn, could you update to the latest version of Files and test if the user experience when creating a new folder is better now ?

**Comment by frankrousseau** [comment]
It's still not working on my Cozy. It's the same for new folders.

**Comment by jsilvestre** [comment]
It's working for me with Chrome. @frankrousseau what is your expected behaviour? It is supposed to be: 
* If I click "new folder",
* then a new folder appears,
* and the form field is empty,
* and the form field's placeholder is "new folder".

**Comment by frankrousseau** [comment]
I tried today and it worked properly. Probably a cache problem.

**Comment by clochix** [comment]
Thanks, closing this. @tykayn, don't hesitate to re-open it if it doesn't work the way you expected it.
