### ISSUE TITLE
Make drop zone bigger for empty folders (initially: Drop files to add them)

### ISSUE THREAD

**Issue by f6fvy** [cozy/cozy-files#310]
A "drop zone" to add files to the current directory would be appreciated.

**Comment by frankrousseau** [comment]
Hi @f6fvy,

 You can already drag and drop file on a folder. It will run the upload process into that folder.

**Comment by f6fvy** [comment]
Very good. I was trying to drop them on a clear area of the page :-(  Silly me.

**Comment by jsilvestre** [comment]
What should be done: in an empty folder, the dropping area is very small, it should have a default height so users are not confused anymore.

Should we move it to enhancement and rephrase the original post/title?

**Comment by clochix** [comment]
@f6fvy the file drop zone is now much bigger, is it ok for you ?

**Comment by f6fvy** [comment]
Much better, thanks ! You can close the issue.
