### ISSUE TITLE
Improve file deletion

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-files#317]
Some users ( @nitot ) are complaining that's it's not easy to discover how to delete a file. Maybe could we add a delete icon when hovering a file.

**Comment by nitot** [comment]
Absolutely. Thank you @clochix for opening this issue. I had someone on the phone explaining me how ot do this yet I had a hard time finding the button. :-/

**Comment by jsilvestre** [comment]
duplicate of https://github.com/cozy/cozy-files/issues/210
