### ISSUE TITLE
Missing german template prevent the application from starting

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-files#318]
As [reported in the forum](https://forum.cozy.io/t/missing-notifmail-js/1066).
Related to cozy-calendar/330.
We should also that this problem doesn't affect other applications.

**Comment by aenario** [comment]
We should probably just remove the internationalized templates and put all strings in the locales files.

**Comment by clochix** [comment]
@aenario I think this is definitively the way to go, but we may need before to simplify the template, to remove some HTML formatting inside strings to translate.

**Comment by poupotte** [comment]
This issue is now fixed.
