### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by elwan** [cozy/cozy-files#323]
Hi guys,
I got this message when i installed Files in cozy {"error":"{ error: 'Application is not authenticated' }"} and it's occurred  with both  installation of  commande line and web store.
thanks

**Comment by clochix** [comment]
Hi @elwan,

This is unfortunately a known random bug. Could you try to uninstall the application and install it again ? If if doesn't work, restarting the Cozy stack should do the job.

Sorry about that, we try to fix this one for very long time, but have hard time reproducing it.

**Comment by clochix** [comment]
Hello @elwan,

Any news on this ?
