### ISSUE TITLE
Can't create folder

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-files#337]
Salut,
Je viens de passer sous file 1.1.11 et j'ai remarquer que vous avez oublier de faire repoper la commande creer un dossier apres avec selectionner quelque chose.

Pour reproduire:

- Selectioner un fichier pour changer le menu en haut a droite (suppression/upload/...)
- Deselectioner le ficher -> on ne peux plus creer de dossiers

bonne chance :smile:

**Comment by frankrousseau** [comment]
Merci pour le rapport de bug @Peltoche !

**Comment by frankrousseau** [comment]
Salut @Peltoche ça devrait être réparé. Tu peux confirmer ?

**Comment by Peltoche** [comment]
Yep, je confirme. Merci a vous!
