### ISSUE TITLE
Bad size in status

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-files#341]
Salut, depuis une versions ou deux le compteur d'espace s'est remis a deconner.

Il m'affiche 348G/3.9G

Sachant deja que c'est plutot 3.9T, cela avait ete reglé dans une version precedente et pour la taille du cozy j'ai pas d'explication... mon cozy.couch fait 1.8G le _users.couch fait 568K et le replicator 8K.

Voili voilou! Bonne chance :smile:

**Comment by clochix** [comment]
Hello @Peltoche,
Tu n'es pas dans le bon dépôt, est-ce que tu peux ré-ouvrir ce ticket dans cozy-home ? Merci !
