### ISSUE TITLE
Update of cozy-files breaks the app

### ISSUE THREAD

**Issue by carrieje** [cozy/cozy-files#353]
I just updated to version 1.1.13
Now, every time I try to access the app, I have a blank page.
Even when I try to open a previously shared folder using the direct URL, it's blank.

I have tried to reboot my instance but it does not solve the issue.
My instance is accessible by you guys if you want to dig a bit around it : carrierjerem.cozycloud.cc

Thanks ;-)

**Comment by frankrousseau** [comment]
Sorry for the wrong publication. Could you try to update your app again?

**Comment by carrieje** [comment]
Working like a charm !
Thanks for the reactivity ;-)

**Comment by frankrousseau** [comment]
Great!
