### ISSUE TITLE
Display problem in navigation bar

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-files#354]
When I navigate in my folders, for some folders, navigation bar seems weird: 
Case 1 : (Problem)
![screenshot from 2015-09-24 08 21 53](https://cloud.githubusercontent.com/assets/2659119/10066662/6201980c-6295-11e5-8d41-7486a571a360.png)

Case 2 : (Classic)
![screenshot from 2015-09-24 08 22 13](https://cloud.githubusercontent.com/assets/2659119/10066665/66b658e2-6295-11e5-8be6-825be15c5925.png)

**Comment by clochix** [comment]
:-S I'm unable to reproduce this one.
![files](https://cloud.githubusercontent.com/assets/384908/10160224/7711e462-669c-11e5-980b-c65dc744356b.png)

What browser are you using ?

**Comment by poupotte** [comment]
I'm using Firefox but issue seems fixed now.

However, on Chronium, I have another bug :/ : 
![screenshot from 2015-09-29 13 39 41](https://cloud.githubusercontent.com/assets/2659119/10162965/a63493d0-66af-11e5-94f9-210b0e2d2470.png)

**Comment by frankrousseau** [comment]
@poupotte Are you sure you are the default zoom level? (ctrl+shift + 0)

**Comment by clochix** [comment]
@poupotte any news ?

**Comment by poupotte** [comment]
Effectively, it works with the default zoom level. I have issues with a zoom out and a zoom in.
