### ISSUE TITLE
Impossible to move a file to a folder where a file with same name exists

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-files#357]
Select a file
Try to move it to another folder in which a file with same file name exist 
**the web client says everything went well**
There is non duplication of the file in the destination folder
The file is not deleted from the origine forlder

I understand the need to prevent moving a file to a folder where there is a file with the same name. But is possible to create such a file (at least from konnectors it was possible).

**Comment by poupotte** [comment]
Fixed on development branch

**Comment by clochix** [comment]
Hello @ZeHiro,
The fix should be available for some days now, could you give it a try?

**Comment by poupotte** [comment]
Thanks @clochix , it works well on production version. @ZeHiro , I close this issue, if you have still this issue, don't hesitate to reopen it.
