### ISSUE TITLE
Node 0.12 compatibility

### ISSUE THREAD

**Issue by nono** [cozy/cozy-files#363]
Hi,

when running the tests for cozy-desktop with node 0.12, I've seen that cozy-files crashes: https://travis-ci.org/cozy-labs/cozy-desktop/jobs/82733299#L1086.

It seems to be a story of dependencies. I *think* it's fixed by https://github.com/form-data/form-data/commit/34c5a2b3dba84c109efcec6d01045e83c9454db3 and we should update request-json-light to use a more recent version of form-data. Then, we should update cozydb to use this new version of request-json-light and, finally, update cozy-files to use this new version of request-json-light.

What do you think?

**Comment by frankrousseau** [comment]
+1

**Comment by frankrousseau** [comment]
@nono can you handle this modification?

**Comment by nono** [comment]
@frankrousseau OK
