### ISSUE TITLE
Disable Casper tests

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-files#366]
Casper tests are no more relevant with the new UI. Should we remove them or fix them?

**Comment by clochix** [comment]
Fix them of course !!!

**Comment by nono** [comment]
It can be the occasion to rewrite them with another tool, as Casperjs seems abandoned: https://github.com/n1k0/casperjs/issues/987 (last comments). I was thinking of [DalekJS](http://dalekjs.com/), but it seems dead also. Maybe [Nightwatch.js](http://nightwatchjs.org/) or [Intern](https://theintern.github.io/).

**Comment by clochix** [comment]
CasperJS may be asleep, but is still amha the best tool for this job, and allow to use different rendering engines, Webkit with PhantomJS or Gecko with SlimerJS
