### ISSUE TITLE
Can't rename a folder with things in it

### ISSUE THREAD

**Issue by nono** [cozy/cozy-files#380]
Hi,

the steps to reprodude:

1. I create a folder `foo` in files
2. In `foo`, I upload two files `bar` and `baz`
3. In `foo`, I create one sub-directory `qux`
4. In `foo/qux`, I upload a file `quux`
5. At the root, I rename `foo` in `foo-renamed`
6. I have a `foo-renamed` folder with my things in it
7. I wait 30s and come back in files
8. I have a `foo` folder, but no `foo-renamed` folder
9. Inside `foo`, I have `qux` but no `bar` or `baz`
10. Inside `foo/qux`, I have no `quux`

**Comment by jsilvestre** [comment]
Apparently 43423a55e9d163b237f66e366343c6570cbb03a7 has fixed this bug. Feel free to reopen if I missed something!

**Comment by jsilvestre** [comment]
Sorry, I should not have closed before it's released.

**Comment by jsilvestre** [comment]
Ok, so indeed there is a waiting time needed to reproduce. 43423a55e9d163b237f66e366343c6570cbb03a7 doesn't fix it, unfortunately.

**Comment by jsilvestre** [comment]
This [user](https://forum.cozy.io/t/quelques-problemes-releves-dans-files/2901) alo has the issue (noted as a reminder to update the topic once it's released).

**Comment by jsilvestre** [comment]
This [user](https://forum.cozy.io/t/quelques-problemes-releves-dans-files/2901) alo has the issue (noted as a reminder to update the topic once it's released).

**Comment by jsilvestre** [comment]
It's been fixed! Forgot to update the issue, here it is! Thanks @nono !
