### ISSUE TITLE
Fix multiple selection

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-files#382]
edit Joseph: Originally this issue is about moving files, but it appears that it is tight to selecting multiple items, and could (more dramatically) be a problem for deletion too.

> See [this thread](https://forum.cozy.io/t/erreur-au-deplacement-de-fichiers-dans-files/1636/1). When moving a file, other files from the same folder are also moved.

> I experimented some strange behaviors:
> - when moving a file, I didn't see all my folders in the dropdown to select target;
> - when moving another file, the previous subfolder I was in was also moved.

**Comment by jsilvestre** [comment]
About your 2.2: my guess is that you can't show folders in the dropdown (especially not current folder and its subfolders).

No idea about the rest before proper investigation.

**Comment by clochix** [comment]
Another user [is experimenting](https://forum.cozy.io/t/appli-files-erreur-de-deplacement-suppression-de-fichiers/2987) the same issue.

**Comment by jsilvestre** [comment]
This issue might be fixed by https://github.com/cozy/cozy-files/commit/43423a55e9d163b237f66e366343c6570cbb03a7
