### ISSUE TITLE
Remove tag input on focusout/escape

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-files#383]
I clicked on the tag icon to add a tag and actually changed my mind (without typing anything). I was surprised to see that even by clicking elsewhere (the input loses the focus) or pressing the <kbd>Esc</kbd> key, the tag input would not go away (until I refreshed the page).

I think removing it when it loses the focus or when the user presses the <kbd>Esc</kbd> key would be nice.

**Comment by poupotte** [comment]
This issue should be now fixed. @nicofrand don't hesitate to reopen this issue if you have still this problem.
