### ISSUE TITLE
Renaming a folder update the path of every files

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-files#387]
When we rename a folder, we update the paths of every files to replace the old name by the new one.
So, if I rename folder `a` to `b`, the path of every file will be updated, replacing the first `a` by `b`.
Files being linked to their folder by their path, and not the folder id, every file whose path contains a `a` will be lost (not deleted, but lost).

**Comment by frankrousseau** [comment]
@clochix what's wrong with it? If the renaming occurs well, no file is lost.

**Comment by clochix** [comment]
I had the following tree:
```
toto
toto1
   file1
```
When I renamed `toto` to `tata`, I lost `file1`, because its path was updated from `toto1` to `tata1`. If I rename the folder `toto1` to `tata1`, I get back `file1`.

**Comment by frankrousseau** [comment]
Ok so the normal behavior is broken.

**Comment by jsilvestre** [comment]
I can confirm that @nono's fix is working, it will be fixed in the next release.
