### ISSUE TITLE
Display more file types inside browser

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-files#417]
A user is asking why he can't display PDF inline inside its browser.

According to [the code](https://github.com/cozy/cozy-files/blob/master/client/app/views/file_view.coffee#L92), when a user click on a file name, application has two behavior:
 - if file is an image, we try to display it;
 - otherwise, we force the download as an attachment.

But browsers are able to display by themselves a lot of file format (PDF, audio, video…) So we should probably extend the image behavior to more file format.

**Comment by poupotte** [comment]
This issue should be fixed with new version : v1.1.22
