### ISSUE TITLE
Cannot drag&drop a file from desktop to browser (Chrome)

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-files#446]
When I drag & drop a file (PNG file, filename without spaces or weird chars) from my desktop file browser to Chrome (Version 49.0.2623.87 (64-bit) on Ubuntu 14.04 in private mode), a wild JS error appears:

```
Uncaught TypeError: Cannot read property 'isFile' of null
```

It works if I do not use the drag&drop.

**Comment by poupotte** [comment]
Duplicated to https://github.com/cozy/cozy-files/issues/436

**Comment by nicofrand** [comment]
:warning: this happens with 1 file only, not several as described in #436 !
