### ISSUE TITLE
Expose API to manage files

### ISSUE THREAD

**Issue by JbIPS** [cozy/cozy-files#476]
I'm wondering if there is a plan to expose an API to manage files in the Cozy.

To give a bit of context, I'm the maintainer of [Unifile](https://github.com/silexlabs/unifile) and I'm working on supporting Cozy as a target. Since 'Files' already take care of simulating a FS, it would be a great start for me.

If your ok with this idea and nobody's already working on it, I'll hack my way through :smile:

**Comment by jsilvestre** [comment]
Hi @JbIPS,

We are rewriting from scratch the Cozy Stack (the server). We put a file system API in it which is exactly what you ask I believe. That means we won't do anything for the current Cozy, but it'll be built-in in the next version. No ETA just yet. 

See the doc [here](https://github.com/cozy/cozy-stack/blob/master/docs/files.md). It's being developed as I write!

**Comment by JbIPS** [comment]
Perfect, I'll wait for the new version :smile: 

Thanks
