### ISSUE TITLE
Better UX for pics and videos

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-files#85]
A user suggests: 
I think it will be great if we can see picture thumbnails of the files that we've downloaded
Possibility to send the video link and have the other person that we sent to click and it plays immediately without downloading

**Comment by poupotte** [comment]
In new version (1.1.19), you can see picture thumbnails on files application.

**Comment by frankrousseau** [comment]
Awesome, thank you!

**Comment by frankrousseau** [comment]
I'll open later an issue about videos separately.

**Comment by poupotte** [comment]
Thanks @frankrousseau :)
